services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  test:
    build: .
    command: ["pytest"]
    volumes:
      - .:/app